name: CI - caller

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  custom-job:
    name: Custom Job
    uses: nightlark/test-reusable-workflow/.github/workflows/ci-reuseable.yml@main
    with:
      username: ${{ github.repository }}
      os: "macos-latest"
