name: CI - reusable

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      os:
        default: 'windows-latest'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  test:
    name: Testing inputs
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Use an input
        run: echo "Hi ${{ inputs.username }}"

  variable-os:
    name: The OS can change!
    runs-on: ${{ inputs.os }}
    steps:
      - name: Print the OS name
        run: echo "Running on ${{ inputs.os }}"

  enter-the-matrix:
    name: Enter the Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Which OS?
        run: echo "Running on ${{ matrix.os }}"
