name: CI - reusable

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Use an input
        run: echo "Hi ${{ inputs.username }}"
